### ISSUE TITLE
Vue2 support

### ISSUE THREAD

**Issue by sobolevn** [callumacrae/vue-test#1]
Hello! 

This package looks really promising, except it does not support `vue@2.0`.
Any plans on updating the dependencies?

**Comment by callumacrae** [comment]
Definitely planning on it, just haven't found the time yet!

I'm not sure if it's just a case of updating the dependencies or if more needs to be changed. The tests are pretty comprehensive, though, so I guess they'd say.

**Comment by callumacrae** [comment]
Working on this today (finally) 🎉

**Comment by callumacrae** [comment]
Released as 1.0.0! 😄 

https://github.com/callumacrae/vue-test/releases/tag/v1.0.0
